### ISSUE TITLE
Not starting ...

### ISSUE THREAD

**Issue by EvilBox** [SteveKueng/munkiwebadmin#10]
Hello,

Suddenly, MunkiWebAdmin does not start. 

**Here is the log:**
` 1924 static files copied to '/munkiwebadmin/static_root'.
 Traceback (most recent call last):
   File "manage.py", line 9, in <module>
     execute_from_command_line(sys.argv)
   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
     utility.execute()
   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
     self.check()
   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
     include_deployment_checks=include_deployment_checks,
   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
     return checks.run_checks(**kwargs)
   File "/usr/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
     new_errors = check(app_configs=app_configs)
   File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
     return check_resolver(resolver)
   File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
     return check_method()
   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
     for pattern in self.url_patterns:
   File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
     res = instance.__dict__[self.name] = self.func(instance)
   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
   File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
     res = instance.__dict__[self.name] = self.func(instance)
   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
     return import_module(self.urlconf_name)
   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
     __import__(name)
   File "/munkiwebadmin/munkiwebadmin/urls.py", line 33, in <module>
     urlpatterns += [url(r'^updates/', include('updates.urls'))]
   File "/usr/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
     urlconf_module = import_module(urlconf_module)
   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
     __import__(name)
   File "/munkiwebadmin/updates/urls.py", line 2, in <module>
     import updates.views
   File "/munkiwebadmin/updates/views.py", line 22, in <module>
     from reposadolib import reposadocommon
 ImportError: No module named reposadolib`

**my docker-compose.yml**
`version: "2.4"

services:
  db:
    image: postgres:9.6
    container_name: mwa2-db
    restart: always
    environment:
      POSTGRES_DB: 'munkiwebadmin'
      POSTGRES_USER: 'munkiwebadmin'
      POSTGRES_PASSWORD: 'munkiwebadmin'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  mwa2:
    image: stevekueng/munkiwebadmin
    container_name: mwa2
    hostname: mwa2
    restart: always
    links:
      - db
    volumes:
      - ./munkirepo:/munkirepo
      - ./reposado:/reposado
    environment:
      DB_HOST: db
      DB_NAME: 'munkiwebadmin'
      DB_USER: 'munkiwebadmin'
      DB_PASS: 'munkiwebadmin'
      VIRTUAL_HOST: mwa.domain.com

  reposado:
    image: mscottblake/reposado
    container_name: mwa2-reposado
    hostname: reposado
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./reposado:/reposado

networks:
  default:
    external:
      name: nginx-proxy`

If you turn off volume reposando, then everything runs without errors. Please tell me how to resolve this problem? Thank you!

**Comment by SteveKueng** [comment]
Hi!

on your volume "reposado" has to be a folder "code/reposadolib" 
otherwise the reposado functionality will not work

if you don't want to use reposado you kann remove the volume reposado

Best,
Steve
