### ISSUE TITLE
Error on Report Submission

### ISSUE THREAD

**Issue by FabianN** [SteveKueng/munkiwebadmin#6]
Hi,

I'm testing out your software and I'm having issues with the reporting method.

It is working to a degree, the Inventory was populated correctly, but the computer lists and the dashboard do not show any indication of a machine's report being submitted.

When I run the either the software manager, the preflight, or postflight, this is the error I can see go by either the web server console or the pre/postflight console:

```
[14/Dec/2015 13:47:04] "POST /update/postflight HTTP/1.1" 500 325806
[14/Dec/2015 13:47:04] "POST /token/new.json HTTP/1.1" 200 65
[14/Dec/2015 13:47:04] "POST /inventory/hash/C07L5026DY3G HTTP/1.1" 200 0
[14/Dec/2015 13:47:04] "POST /token/new.json HTTP/1.1" 200 65
Internal Server Error: /inventory/submit
Traceback (most recent call last):
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/tokenapi/decorators.py", line 33, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/Shared/munkiwebadmin_env/munkiwebadmin/inventory/views.py", line 98, in submit
    machine.save()
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Shared/munkiwebadmin_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: reports_machine.imagr_workflow may not be NULL
[14/Dec/2015 13:47:08] "POST /inventory/submit HTTP/1.1" 500 578267
```

**Comment by SteveKueng** [comment]
Hi,
witch commit did you use?
Please try the newest one or the last release tag
